language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
sudo: false
script: mvn clean package
after_success:
  - mvn clean test cobertura:cobertura coveralls:report
  - bash <(curl -s https://codecov.io/bash)
